# Network
GLIMPSE: 8
HIDDEN_SIZE: 1024
K_TIMES: 3
DROPOUT_R: 0.2
CLASSIFER_DROPOUT_R: 0.5
FLAT_MLP_SIZE: 512
FLAT_GLIMPSES: 1
FLAT_OUT_SIZE: 2048

# Execution
BATCH_SIZE: 512
LR_BASE: 0.001
LR_DECAY_R: 0.25
LR_DECAY_LIST: [11, 13]
WARMUP_EPOCH: 4
MAX_EPOCH: 13
GRAD_NORM_CLIP: -1
GRAD_ACCU_STEPS: 1
OPT_BETAS_0: 0.9
OPT_BETAS_1: 0.98