# Network
HIGH_ORDER: True #True for MFH, False for MFB
HIDDEN_SIZE: 512
MFB_K: 5
MFB_OUT_SIZE: 1000
LSTM_OUT_SIZE: 1024
LSTM_DROPOUT_R: 0.3
MFB_DROPOUT_R: 0.1
NUM_IMG_GLIMPSES: 2
NUM_QUES_GLIMPSES: 2

# Execution
LOSS: KLDiv
BATCH_SIZE: 64
VAL_BATCH_SIZE: 64
LR_BASE: 0.0007
LR_DECAY_R: 0.25
LR_DECAY_LIST: [6, 12, 13]
WARMUP_EPOCH: 0
MAX_EPOCH: 13
GRAD_NORM_CLIP: 10
GRAD_ACCU_STEPS: 1
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.99)', eps: '1e-9'}

